# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - editorcloudfx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_1669fe42511642738ab4da4943822e9a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d10ea02c4f64381adf551cdc8efd212 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_1669fe42511642738ab4da4943822e9a }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'editorcloudfx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_392b55c19d6a4a54ad783f10083f2ded }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_1669fe42511642738ab4da4943822e9a }}/appsvc/staticsite:${{ github.sha }}'